apps/accounts/api/urls.py
from django.urls import path, include

from .views import ApiRoot, UserList, Logout, Login, SignupApiView

urlpatterns = [
    # Accounts
    path('accounts/users/', UserList.as_view(), name=UserList.name),
    path('accounts/login/', Login.as_view(), name=Login.name),
    path('accounts/signup/', SignupApiView.as_view(), name=SignupApiView.name),
    path('accounts/logout/', Logout.as_view(), name=Logout.name),

    path('', include('apps.tasks.api.urls') ),

    path('', ApiRoot.as_view(), name=ApiRoot.name),
]

apps/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views
from .views import PasswordResetConfirmView
from .forms import CustomPasswordResetForm

from .views import *

app_name = "accounts"

urlpatterns = [
    path('signup/', SignUpView.as_view(), name=SignUpView.name),
    path('accounts/login/', LoginView.as_view(), name=LoginView.name),
    path('accounts/logout/', LogoutView.as_view(), name="logout"),

    path('accounts/password_reset/',
        views.PasswordResetView.as_view(
            template_name='accounts/registration/password_reset_form.html',
            form_class=CustomPasswordResetForm,
            email_template_name='accounts/registration/password_reset_email.html',
            success_url=reverse_lazy('accounts:password_reset_done')
         ), name='password_reset'),

    path('accounts/password_reset/done/', views.PasswordResetDoneView.as_view(
        template_name='accounts/registration/password_reset_done.html'
    ), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', views.PasswordResetCompleteView.as_view(
        template_name = 'accounts/registration/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('accounts/password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('profile/', MyProfile.as_view(), name=MyProfile.name),
    path('profile/<int:pk>/', EditProfileView.as_view(), name=EditProfileView.name),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

    path('', RedirectView.as_view(pattern_name='accounts:login', permanent=False), name='home'),
    path('', include('apps.accounts.urls', namespace='accounts')),
    path('', include('apps.tasks.urls', namespace='tasks')),

    # Backend API
    path('api/<str:version>/', include('apps.accounts.api.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser, BaseUserManager
from simple_history.models import HistoricalRecords


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        import random
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


def create_route_avatar(instance, filename):
    path = 'avatars/{username}/{name}'.format(
        username=instance.username, name=filename
    )
    return path


class PersonAbstract(models.Model):
    """
    Person Abstract model based in profile information
    """

    class GENDER(models.TextChoices):
        NO_SPECIFY = 'no_specify', _('No specify')
        MEN = 'men', _('Men')
        WOMEN = 'women', _('Women')

    class TYPE_DOCUMENT(models.TextChoices):
        NO_SPECIFY = 'no_specify', _('No specify')
        CITIZENDSHIP_CARD = 'citizenship_card', _('Citizenship card')
        IDENTITY_CARD = 'identity_card', _('Identity card')
        FOREIGNER_ID = 'foreigner_id', _('Foreigner id')
        PASSPORT = 'passport', _('Passport')

    gender = models.CharField(max_length=10, choices=GENDER.choices,
        default=GENDER.NO_SPECIFY, blank=True, null=True, verbose_name=_('Gender'))
    address = models.CharField(max_length=30, blank=True, null=True,
        verbose_name=_('Address'), help_text=_('Address.'))
    phone = models.CharField(max_length=30, blank=True, null=True,
        verbose_name=_('Phone'), help_text=_('user phone.'))
    document_number = models.BigIntegerField(null=True, blank=True,
        unique=True, verbose_name=_('Document number'),
        help_text=_('This number is unique and cannot be changed once registered..'))
    type_document = models.CharField(max_length=20, choices=TYPE_DOCUMENT.choices,
        default=TYPE_DOCUMENT.NO_SPECIFY, blank=True, null=True, verbose_name=_('Type document'))

    class Meta:
        abstract = True


class User(PersonAbstract, AbstractUser):
    """
    User model based in abstract user for profile information
    """
    # making the email username
    username = None
    email = models.EmailField(unique=True, error_messages={'unique': _("A user with this email already exists."), },
        verbose_name=_('Email address'),
        help_text=_('The email address is the same username.'))
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    avatar = models.ImageField(max_length=255, upload_to=create_route_avatar, blank=True, null=True,
        verbose_name=_('Profile picture'), help_text=_('User profile picture'))

    objects = UserManager()

    history = HistoricalRecords()

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        if not self.first_name or not self.last_name:
            # without full name return the email username.
            return '{}'.format(self.email.split('@')[0])
        else:
            return '{}'.format(self.get_full_name())

    @property
    def email_username(self):
        return '{}'.format(self.email.split('@')[0])

    @property
    def get_avatar(self):
        if self.avatar:
            return self.avatar.url
        else:
            return None

apps/accounts/api/views.py
from django.contrib import auth
from django.utils.translation import gettext_lazy as _
from rest_framework import status, generics
from rest_framework.reverse import reverse
from rest_framework.response import Response
from rest_framework.permissions import AllowAny, IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework.authentication import TokenAuthentication
from rest_framework.views import APIView
from rest_framework_simplejwt.tokens import RefreshToken

from apps.tasks.api.views import TaskList
from .serializers import UserSerializer
from .permissions import IsOwnerOrReadOnly
from .pagination import UserPageNumberPagination

from ..models import User
from ..forms import SignUpForm
from ..tasks import send_mail

class UserList(generics.ListCreateAPIView):
    serializer_class = UserSerializer
    queryset = User.objects.filter(is_superuser=False)
    name = 'Users List'
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]
    authentication_class = (TokenAuthentication,)
    pagination_class = UserPageNumberPagination


class Login(APIView):
    name = 'Api Login'
    permission_classes = (AllowAny, )

    def post(self, request, version):
        """
        Send the auth data to celery and if it returns true we create jwt
        The jwt is created with refresh and access,
        which will be used to access a protected route with the bearer flag
        tThe session that sends the expiration time to the cookie is created,
        the time is configured in SETTINGS
        """
        auth_result = ''
        username = request.data.get('username')
        password = request.data.get('password')

        user = User.objects.filter(email=username).first()
        if user and user.check_password(password):
            refresh = RefreshToken.for_user(user)
            res = {
                "refresh": str(refresh),
                "access": str(refresh.access_token),
            }
            return Response(res, status=status.HTTP_200_OK)
        else:
            res = {
                "message": 'Invalid credentials',
            }
            return Response(res, status=status.HTTP_401_UNAUTHORIZED)


class Logout(APIView):
    name = 'Api Logout'
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]
    authentication_class = (TokenAuthentication,)

    def post(self, request, version):
        """
        From the cache we get the jwt and send it to the blacklist
        if there is the token is exp also the session and cookies are destroyed
        """
        refresh = RefreshToken.for_user(request.user)
        auth.logout(request)
        if refresh:
            refresh.blacklist()
        res = {
            "detail": 'Session ending',
        }
        return Response(res, status=status.HTTP_205_RESET_CONTENT)


class SignupApiView(APIView):
    """
    Create a new user and register this account
    """
    name = 'Sign Up'
    permission_classes = (AllowAny, )

    def post(self, request, version):
        """
        register a new user
        :param request:
        :param version:
        :return: success or serialized errors
        """
        group = self.request.data.get('group', 'host')
        form = SignUpForm(self.request.POST, self.request.FILES)
        if not form.is_valid():
            errors = dict(form.errors.items())
            return Response([{
                'status': 'error',
                'msg': _('can not create user, data errors'),
                'data': errors
            }],
                status=status.HTTP_400_BAD_REQUEST)
        user = form.save()
        serializer = UserSerializer(user)

        refresh = RefreshToken.for_user(user)
        auth_tokens = {
            'refresh': str(refresh),
            'access': str(refresh.access_token),
        }
        send_mail.delay(request.get_host(), user.id)
        return Response([{
            'status': 'success',
            'msg': _('user {} created successfully.').format(user.get_full_name()),
            'version': version,
            'data': serializer.data,
            'auth_tokens': auth_tokens
        }], status=status.HTTP_200_OK)


class ApiRoot(generics.GenericAPIView):
    name = 'api-root'
    permission_classes = (IsAuthenticatedOrReadOnly,)

    def get(self, request, *args, **kwargs):
        return Response({
            'users': reverse(UserList.name, request=request, kwargs=kwargs),
            'tasks': reverse(TaskList.name, request=request, kwargs=kwargs),
        })

apps/accounts/views.py
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.db import transaction
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import views, login
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, UpdateView

from apps.commons.helpers import uw_add_alert

from .models import User
from .tasks import send_mail
from .decorators import is_superuser
from .forms import CustomSetPasswordForm, CustomAuthenticationForm, SignUpForm, EditProfileForm


class SignUpView(CreateView):
    """
    Register a New user to the app creating a :model:`accounts.User`.
    **Context**
    ``object``
        An instance of :model:`accounts.User`.
    **Template:**
    :template:`accounts/user_form.html`
    """
    name = 'signup'
    model = User
    form_class = SignUpForm
    template_name = 'accounts/registration/signup.html'
    success_url = reverse_lazy('accounts:login')
    success_msg = _('You have successfully registered on the Elenas platform.!')

    @transaction.atomic
    def form_valid(self, form):
        """If the form is valid, save the user as inactive and a confirmation email is sent."""
        sid = transaction.savepoint()
        try:
            user = form.save(commit=False)
            user.username = self.request.POST.get('username')
            user.set_password( self.request.POST.get('password'))
            user.is_active = True
            user.save()
            uw_add_alert(self.request, self.success_msg, "success")
            transaction.savepoint_commit(sid)
            transaction.on_commit(lambda: send_mail.delay(self.request.get_host(), user.id))
            return super(SignUpView, self).form_valid(form)
        except Exception as e:
            uw_add_alert(self.request, e, "error")
            transaction.savepoint_rollback(sid)
        return super().form_invalid(form)


@method_decorator(is_superuser, name='dispatch')
class LoginView(views.LoginView):
    name = 'login'
    form_class = CustomAuthenticationForm
    template_name = 'accounts/registration/login.html'


    def get_success_url(self):
        if self.request.user.is_authenticated and self.request.user.is_superuser:
            return reverse_lazy('admin:index')
        else:
            return reverse_lazy('accounts:my_profile')

    def form_valid(self, form):
        """Security check complete. Log the user in."""
        login(self.request, form.get_user())
        return HttpResponseRedirect(self.get_success_url())


@method_decorator(login_required, name='dispatch')
class LogoutView(views.LogoutView):
    name = 'logout'
    template_name = 'accounts/registration/logged_out.html'


class PasswordResetConfirmView(views.PasswordResetConfirmView):
    form_class = CustomSetPasswordForm
    template_name = 'accounts/registration/password_reset_confirm.html'
    success_msg = _('Your password has been changed successfully!')

    def form_valid(self, form):
        """If the form is valid, save the user as inactive and a confirmation email is sent."""
        form.save()
        uw_add_alert(self.request, self.success_msg, "success")
        return redirect('accounts:login')

@method_decorator(login_required, name='dispatch')
class MyProfile(UpdateView):
    """
    View to see the profile of the user authenticated.
    """
    name = 'my_profile'
    model = User
    form_class = EditProfileForm
    success_url = reverse_lazy('accounts:my_profile')
    success_msg = _('Your profile has been updated successfully!')

    def get_object(self, **kwargs):
        ## this is to get the object without the user id, override the id with the current user
        return get_object_or_404(self.model.objects.select_related(None),
                                 pk=self.request.user.id)

    def form_valid(self, form):
        uw_add_alert(self.request, self.success_msg, "success")
        return super(MyProfile, self).form_valid(form)


@method_decorator(login_required, name='dispatch')
class EditProfileView(UpdateView):
    """
    View to edit the profile of the user authenticated.
    """
    name = 'edit_profile'
    model = User
    form_class = EditProfileForm
    template_name = 'accounts/user_detail.html'
    success_url = reverse_lazy('accounts:my_profile')
    success_msg = _('Your profile has been updated successfully.')

    def form_valid(self, form):
        uw_add_alert(self.request, self.success_msg, "success")
        return super(EditProfileView, self).form_valid(form)

apps/accounts/templates/accounts/accounts_base.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'navbar.html' with active='user'  %}
{% endblock %}

apps/accounts/templates/accounts/user_form.html
{% extends 'accounts/accounts_base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}
	{% if request.user.id == object.id %}
		{% trans 'My Profile' %} {{ object.get_full_name }}
	{% else %}
		{% trans 'profile of' %} {{ object.get_full_name }}
	{% endif %}
{% endblock %}

{% block styles %}
	{{ form.media.css }}
	{{ form.media.js }}
{% endblock %}

{% block content %}

	<div class="mt-4 px-5">
		{% if messages %}
			{% for message in messages %}
				<div class="text-center alert alert-success" role="alert">
					{{ message }}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			{% endfor %}
		{% endif %}
	</div>

<div class=" mb-5">
		<form method="post" enctype="multipart/form-data" class="update-form">
			{% csrf_token %}
			{% for hidden in form.hidden_fields %}
				{{ hidden }}
			{% endfor %}
			<div class="row mb-5">
				<div class="col-12">
					<div class="card shadow-sm p-5 no-border-radius">
						<div class="card-body">
							<div class="row">
								<div class="col-12 col-sm-12 col-md-3 col-lg-3">
									<div class="avatar-wrapper my-auto img-avata-bg-big">
										<img class="profile-pic" src="{% if request.user.get_avatar %}{{ request.user.get_avatar }}{% else %}{% static '/images/user.jpg' %}{% endif %}"/>
										<div class="upload-button">
											<i class="fa fa-arrow-circle-up" aria-hidden="true"></i>
										</div>
										<input class="file-upload" type="file" accept="image/*" name="avatar"
										       id="id_avatar"/>
									</div>
								</div>
								<div class="col-12 col-sm-12 col-md-9 col-lg-9">
									<h3 class="font-size-30 font-weight-normal text-orange">
										{{ form.instance.first_name }} {{ form.instance.last_name }}
									</h3>
									<p><i class="fa fa-envelope mr-2 text-orange"></i> {{ form.instance.email }}</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="row equal">
				<div class="col-sm-12 col-md-6 col-lg-6 col-6">
					<div class="card shadow-sm p-5 no-border-radius flex-fill">
						<div class="card-body">
							<div class="row ">
								<div class="col-12 col-sm-12 col-md-12 col-lg-12 mb-4">
									<label class="text-gray-666 font-weight-bold" for="id_first_name">
										{{ form.first_name.label }}:
									</label>
									{{ form.first_name }}
									<div class="text-danger">
										{{ form.first_name.errors }}
									</div>
								</div>
								<div class="col-12 col-sm-12 col-md-12 col-lg-12 mb-4">
									<label class="text-gray-666 font-weight-bold" for="id_last_name">
										{{ form.last_name.label }}:
									</label>
									{{ form.last_name }}
									<div class="text-danger">
										{{ form.last_name.errors }}
									</div>
								</div>
								<div class="col-12 col-sm-12 col-md-12 col-lg-12">
									<label class="text-gray-666 font-weight-bold" for="id_last_name">
										{{ form.gender.label }}:
									</label>
									{{ form.gender }}
									<div class="text-danger">
										{{ form.gender.errors }}
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="col-sm-12 col-md-6 col-lg-6 col-6">
					<div class="card shadow-sm p-5 no-border-radius flex-fill">
						<div class="card-body">
							<div class="row">
								<div class="col-12 col-sm-12 col-md-12 col-lg-12 mb-4">
									<label class="text-gray-666 font-weight-bold"
									       for="id_phone">{{ form.phone.label }}:</label>
									{{ form.phone }}
									<div class="text-danger">
										{{ form.phone.errors }}
									</div>
								</div>

								<div class="col-12 col-sm-12 col-md-12 col-lg-12 mb-4">
									<label class="text-gray-666 font-weight-bold"
									       for="id_phone">{{ form.address.label }}:</label>
									{{ form.address }}
									<div class="text-danger">
										{{ form.address.errors }}
									</div>
								</div>

								<div class="col-12 col-sm-12 col-md-5 col-lg-5">
									<label class="text-gray-666 font-weight-bold"
									       for="id_country">{{ form.type_document.label }}: <small class="not-found"></small></label>
									{{ form.type_document }}
									<div class="text-danger">
										{{ form.type_document.errors }}
									</div>
								</div>

								<div class="col-12 col-sm-12 col-md-7 col-lg-7">
									<label class="text-gray-666 font-weight-bold"
									       for="id_country">{{ form.document_number.label }}: <small class="not-found"></small></label>
									{{ form.document_number }}
									<div class="text-danger">
										{{ form.document_number.errors }}
									</div>
								</div>
							</div>

						</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col text-right">
					<button type="submit"
						class="btn btn-blue rounded text-uppercase font-weight-500 mt-4"
					    name="save_redirect" value="REDIRECT">
						{% trans "save" %}
						<i class="fa fa-save float-left mr-2 mt-1"></i>
					</button>
				</div>
			</div>
		</form>
	</div>
{% endblock %}

{% block scripts %}
	<script type="text/javascript">
		$(document).ready(function () {

			var readURL = function (input) {
				if (input.files && input.files[0]) {
					var reader = new FileReader();
					reader.onload = function (e) {
						$('.profile-pic').attr('src', e.target.result);
					};
					reader.readAsDataURL(input.files[0]);
				}
			};

			$(".file-upload").on('change', function () {
				readURL(this);
			});

			$(".upload-button").on('click', function () {
				$(".file-upload").click();
			});
		});
	</script>
{% endblock %}