apps/tasks/api/urls.py
from django.urls import path, include

from .views import TaskList, TaskUpdateDestroyView

urlpatterns = [
    # Tasks
    path('tasks/', TaskList.as_view(), name=TaskList.name),
    path('tasks/<int:pk>/', TaskUpdateDestroyView.as_view(), name=TaskUpdateDestroyView.name),
]

apps/tasks/urls.py
from django.urls import path

from .views import *

app_name = "tasks"

urlpatterns = [
    path('tasks/', TasksListView.as_view(), name=TasksListView.name),
    path('tasks/create', TaskView.as_view(), name='task_create'),
    path('tasks/<int:pk>/update/', TaskView.as_view(), name='task_update'),
    path('tasks/<int:pk>/delete/', TaskDeleteView.as_view(), name=TaskDeleteView.name),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

    path('', RedirectView.as_view(pattern_name='accounts:login', permanent=False), name='home'),
    path('', include('apps.accounts.urls', namespace='accounts')),
    path('', include('apps.tasks.urls', namespace='tasks')),

    # Backend API
    path('api/<str:version>/', include('apps.accounts.api.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/tasks/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from simple_history.models import HistoricalRecords


from apps.accounts.models import User
from apps.commons.models import AuditBaseAbstract

class Task(AuditBaseAbstract):
    """
    Task model.
    """
    name = models.CharField(max_length=100, verbose_name=_('name'),
        help_text=_('Descriptive task name'))
    description = models.TextField(verbose_name=_('description'),
        help_text=_('Task description'), blank=True, null=True)
    is_completed = models.BooleanField(default=False, verbose_name=_('is completed?'),
        help_text=_('Check if the task is complete'))
    user = models.ForeignKey(User, on_delete=models.CASCADE, )

    history = HistoricalRecords()

    class Meta:
        verbose_name = _("Task")
        verbose_name_plural = _("Tasks")

    def __str__(self):
        return "{} - {}".format(self.description, self.user)

apps/tasks/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Task

class TaskForm(forms.ModelForm):
    """
    Task form for tasks.
    """
    class Meta:
        model = Task
        fields = '__all__'
        """
        widgets = {
            'name': forms.TextInput(
                attrs={'placeholder': 'Task', 'autofocus': True, 'class': 'form-control search-round'}
            ),
        }
        """
        exclude = ['user', ]

apps/tasks/api/views.py
from django.utils.translation import gettext_lazy as _
from rest_framework import status, generics
from rest_framework.permissions import AllowAny, IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework.authentication import TokenAuthentication


from .serializers import TaskSerializer
from .permissions import IsOwnerOrReadOnly
from .pagination import TaskPageNumberPagination

from ..models import Task


class TaskList(generics.ListCreateAPIView):
    """
    Tasl List or Task Create View
    """
    serializer_class = TaskSerializer
    queryset = Task.objects.all()
    name = 'Tasks List'
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]
    authentication_class = (TokenAuthentication,)
    pagination_class = TaskPageNumberPagination

    def get_queryset(self):
        user = self.request.user  # Current User
        is_completed = self.request.GET.get('status')
        description = self.request.GET.get('description')
        kwargs = {}
        if is_completed:
            kwargs['is_completed'] = is_completed
        if description:
            kwargs['description__icontains'] = description

        return Task.objects.filter(user=user, **kwargs)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class TaskUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    name = 'Task Update and destroy'
    lookup_field = 'pk'
    authentication_classes = (TokenAuthentication,)
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]

apps/tasks/views.py
from django.db.models import Q
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView

from apps.commons.views import CreateAndUpdateViewMixin
from apps.commons.helpers import uw_add_alert

from .models import Task
from .forms import TaskForm

class TasksListView(ListView):
    """
    List view for tasks
    """
    name = 'task_list'
    model = Task
    paginate_by = 5

    def get_queryset(self, tab=None):
        """
        Queryset giving only the current forms
        """
        keyword = self.request.GET.get('keyword', None)
        queryset = self.model.objects.filter(user=self.request.user).order_by('-id')
        if keyword:
            queryset = self.model.objects.filter(
                Q(description__icontains=keyword) | Q(user__first_name__icontains=keyword) | Q(user__last_name__icontains=keyword)
            )
        return queryset



class TodoListView(ListView):
    """
    List view for fields
    """
    name = 'todo_list'
    model = Task
    template_name = 'tasks/todo_list.html'


class TaskView(CreateAndUpdateViewMixin):
    """
    Tasks view (create and update)
    """
    form_class = TaskForm
    model = Task
    success_url = reverse_lazy("tasks:task_list")
    success_msg = _('Your data has been saved correctly!')

    def form_valid(self, form, **kwargs):
        """
        Validate and save the tasks with create or update option
        """
        try:
            obj = form.save(commit=False)
            obj.user_id = self.request.user.id
            obj.save()
            uw_add_alert(self.request, self.success_msg, "success")
            return redirect(self.success_url)
        except Exception as e:
            uw_add_alert(self.request, e, "error")
        return super().form_invalid(form)

    def form_invalid(self, form, **kwargs):
        print(form)
        return super().form_invalid(form)


@method_decorator(login_required, name='dispatch')
class TaskDeleteView(DeleteView):
    """
    Task delete view for Shipment
    """
    name = 'task_delete'
    model = Task
    success_url = reverse_lazy('tasks:task_list')

apps/tasks/templates/tasks/task_confirm_delete.html
{% load i18n %}

{% if object %}
    {% trans 'delete task'|title as modal_title %}
    {% url 'tasks:task_delete' object.id as url_delete %}
{% endif %}

<form action="{{ url_delete }}" method="post">
    {% csrf_token %}
    <p>{% trans '¿Are you sure you want to delete' %} "{{ object }}"?</p>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'close'|title %}</button>
        <button type="submit" class="btn btn-danger" name="{% trans 'delete'|title %}">
            <i class="fas fa-trash-alt mr-2"></i> {{ modal_title }}
        </button>
    </div>
</form>

apps/tasks/templates/tasks/task_form.html
{% load static %}
{% load i18n %}

{% if object %}
    {% trans 'update task'|title as modal_title %}
    {% url 'tasks:task_update' object.id as url_view %}
{% else %}
    {% trans 'add task'|title as modal_title %}
    {% url 'tasks:task_create' as url_view %}
{% endif %}

<form action="{{ url_view }}" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-12">
            <h3 class="text-center text-gray-666">{{ modal_title }}</h3>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 px-5 pt-2 text-gray-666">
            <div class="card shadow-sm mb-4">
                <div class="card-body">
                    <div class="form-group row">
                        <label class="text-gray-666 font-weight-bold col-12">{{ form.name.label }}</label>
                        <div class="col-12">
                            {{ form.name }}
                            <div class="text-danger">
                                {{ form.name.errors }}
                            </div>
                            <small id="descriptionHelpBlock" class="form-text text-muted">
                                {{ form.name.help_text }}
                            </small>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="text-gray-666 font-weight-bold col-12">{{ form.description.label }}</label>
                        <div class="col-12">
                            {{ form.description }}
                            <div class="text-danger">
                                {{ form.description.errors }}
                            </div>
                            <small id="descriptionHelpBlock" class="form-text text-muted">
                                {{ form.description.help_text }}
                            </small>
                        </div>
                    </div>
                    {% if object %}
                    <div class="form-row mt-4">
                        <div class="form-group col-md-12">
                            {{ form.is_completed.label_tag }}
                            {{ form.is_completed }}
                            <div class="text-danger">
                                {{ form.is_completed.errors }}
                            </div>
                            <small id="stateHelpBlock" class="form-text text-muted">
                                {{ form.is_completed.help_text }}
                            </small>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-12 text-right my-2">
                <button type="button" class="btn btn-secondary text-uppercase mr-3" data-dismiss="modal">
                    {% trans 'cancel'|title %}
                    <i class="fa fa-chevron-left float-left mr-2 mt-1"></i>
                </button>
                <button class="btn btn-save-blue text-uppercase" type="submit"
                    name="{% if object %}{% trans 'update'|title %}{% else %}{% trans 'save'|title %}{% endif %}">
                    {% if object %}{% trans 'update'|title %}{% else %}{% trans 'save'|title %}{% endif %}
                    <i class="fa fa-save float-left mr-2 mt-1"></i>
                </button>
            </div>
        </div>
    </div>
</form>

apps/tasks/templates/tasks/task_list.html
{% extends 'tasks/tasks_base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
	{% trans 'Tasks' %}
{% endblock %}

{% block content %}
	<div class="container-fluid mb-5">

		<div class="container-fluid border-top-1px-gray" style="margin-top: -1px;">
			<div class="row">
				<div class="col-12">
					<div class="mt-4 px-5">
					{% if messages %}
						{% for message in messages %}
						<div class="text-center alert alert-success" role="alert">
							{{ message }}
							<button type="button" class="close" data-dismiss="alert" aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
						</div>
						{% endfor %}
					{% endif %}
					</div>
				</div>
			</div>
			<div class="row pt-5 pb-4">
				<div class=" col-12 col-sm-6 col-md-6 col-lg-5 pl-0 search-bar">
					<form method="get">
						<div class="input-group">
							<input type="text" class="form-control search-round" name="keyword" id="id_keyword" placeholder="{% trans 'search'|title %}" aria-label="{% trans 'search'|title %}" aria-describedby="button-search">
							<div class="input-group-append">
								<button class="btn btn-gray-EE" type="submit" id="button-search" data-toggle="tooltip" data-placement="bottom" title="{% trans 'search'|title %}">
									<i class="fa fa-search"></i>
								</button>
								<a href="{% url 'tasks:task_list' %}" class="btn btn-gray-EE search-refresh" data-toggle="tooltip" data-placement="bottom" title="{% trans 'clean search'|title %}">
									<i class="fas fa-redo-alt"></i>
								</a>
							</div>
						</div>
					</form>
				</div>
				<div class="col-12 col-sm-6 col-md-6 col-lg-7 pr-0 text-left text-sm-right text-md-right text-lg-right">
					<a class="btn btn-blue2 text-uppercase" title="{% trans 'add'|title %}" role="button"
						onclick="CreateAndUpdateTask('{% url "tasks:task_create" %}');"
						href="javascript:void(0);"
						data-toggle="modal" data-target=".bd-example-modal-lg">
						{% trans "add"|title %}
						<i class="fas fa-plus-circle float-left mr-2 mt-1"></i>
					</a>
				</div>
				{% include 'tasks/utils/_create_task.html' %}
			</div>

			<div class="row bg-white" role="tabpanel">
				<div class="col-lg-12 table-responsive px-0">
					<table class="table table-hover">
						<thead>
							<tr class="font-weight-500 text-gray-666 text-capitalize">
								<th scope="col" class="align-middle border-top-0 border-left pr-0">{% trans '#' %}</th>
								<th scope="col" class="align-middle border-top-0 pr-0"><div class="border-right">{% trans 'user' %}</div></th>
								<th scope="col" class="align-middle border-top-0 pr-0"><div class="border-right">{% trans 'description'|title %}</div></th>
								<th scope="col" class="align-middle border-top-0 pr-0"><div class="border-right">{% trans 'status'|title %}</div></th>
								<th scope="col" class="align-middle border-top-0 pr-0 text-center"><div class="border-right">{% trans 'actions'|title %}</div></th>
							</tr>
						</thead>
						<tbody class="font-weight-300">
						{% for task in object_list %}
							{% include 'tasks/utils/_row_task.html' %}
						{% empty %}
							<tr>
								<td class="text-center" colspan="7">{% trans 'You have no tasks yet' %}</td>
							</tr>
						{% endfor %}
						</tbody>
					</table>
					{% include 'utils/_paginator.html' %}
				</div>
			</div>
			{% include 'tasks/utils/_delete_task.html' %}
		</div>
	</div>

{% endblock %}


{% block scripts %}
    <script>
        function DeleteTask(url) {
            $('.modal-body').load(url,function(){
                $('#deleteTask').modal({show:true});
            });
        }
        function CreateAndUpdateTask(url) {
        	$('.modal-body').load(url,function(){
                $('#createTask').modal({show:true});
            });
        }
        document.getElementById("year").innerHTML = new Date().getFullYear();
    </script>
{% endblock scripts %}

{% block fixed-bottom %}fixed-bottom{% endblock %}

apps/tasks/templates/tasks/tasks_base.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'navbar.html' with active='todo list'  %}
{% endblock %}

apps/tasks/templates/tasks/todo_list.html
{% extends 'tasks/tasks_base.html' %}
{% load static %}
{% load i18n %}

{% block navbar %}
{% include 'navbar.html' with active='todo list'  %}
{% endblock %}

{% block title %}
	{% trans 'Todo List' %}
{% endblock %}

{% block content %}
	<div class="container-fluid mb-5">
		<div class="container-fluid border-top-1px-gray" style="margin-top: -1px;">
			<div class="row pt-5 pb-4">
				<div class=" col-12 col-sm-6 col-md-6 col-lg-4 pl-0 search-bar">
					<form method="get">
						<div class="input-group">
							<input type="text" class="form-control search-round" name="keyword" id="id_keyword" placeholder="{% trans 'search'|title %}" aria-label="{% trans 'search'|title %}" aria-describedby="button-search">
							<div class="input-group-append">
								<a href="javascript:void(0);" id="id_search" class="btn btn-gray-EE search-refresh" data-toggle="tooltip" data-placement="bottom" title="{% trans 'clean search'|title %}">
									<i class="fas fa-redo-alt"></i>
								</a>
							</div>
						</div>
					</form>
				</div>

				<div class=" col-12 col-sm-6 col-md-6 col-lg-8 pl-0 search-bar">
					<form method="get">
						<div class="input-group">
							<input type="text" class="form-control search-round" name="task" id="id_task" placeholder="{% trans 'Description task' %}" aria-label="{% trans 'description'|title %}" aria-describedby="button-search">
							<div class="input-group-append">
								<a href="javascript:void(0);" onclick="AddTask();" class="btn btn-green-EE search-refresh" data-toggle="tooltip" data-placement="bottom" title="{% trans 'add task'|title %}">
									<i class="fas fa-plus mr-2"></i> {% trans 'add'|title %}
								</a>
							</div>
						</div>
					</form>
				</div>
			</div>

			<div class="row bg-white" role="tabpanel">
				<div class="col-lg-12 table-responsive px-0">
					<table class="table table-hover">
						<thead>
							<tr class="font-weight-500 text-gray-666 text-capitalize">
								<th scope="col" class="align-middle border-top-0 border-left pr-0">{% trans '#' %}</th>
								<th scope="col" class="align-middle border-top-0 pr-0"><div class="border-right">{% trans 'user' %}</div></th>
								<th scope="col" class="align-middle border-top-0 pr-0"><div class="border-right">{% trans 'description'|title %}</div></th>
								<th scope="col" class="align-middle border-top-0 pr-0"><div class="border-right">{% trans 'status'|title %}</div></th>
								<th scope="col" class="align-middle border-top-0 pr-0 text-center"><div class="border-right">{% trans 'actions'|title %}</div></th>
							</tr>
						</thead>
						<tbody class="font-weight-300">
						{% for task in object_list %}
							{% include 'tasks/utils/_row_task.html' %}
						{% empty %}
							<tr>
								<td class="text-center" colspan="7">{% trans 'You have no tasks yet' %}</td>
							</tr>
						{% endfor %}
						</tbody>
					</table>
					{% include 'utils/_paginator.html' %}
				</div>
			</div>
		</div>
	</div>

{% endblock %}


{% block scripts %}
    <script>

		const xhr = async (url, type, data) => {
			return await $.ajax({
				url: url,
				type: type,
				contentType: 'application/json',
				dataType: 'json',
				data: data,
				beforeSend: function (xhr) {
					xhr.setRequestHeader("X-CSRFToken", "{{csrf_token}}");
				},
				success: function (data) {
					return data;
				}
			});
		};

        function AddTask(){
			var task = $("#id_task").val();
			if( task ){
				var url = "{% url 'Users List' 'v1' %}";
				const res = xhr(url, 'GET');
				res.then((obj) => {
					var results = obj['results'][0];
					console.log(obj)
					console.log(results)

				});
			}
		}

        document.getElementById("year").innerHTML = new Date().getFullYear();
    </script>
{% endblock scripts %}

{% block fixed-bottom %}fixed-bottom{% endblock %}